language: rust

before_script:
  - psql -c 'create database cargo_registry_test;' -U postgres

script:
  - cargo build
  - cargo test

addons:
  postgresql: "9.3"

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - S3_BUCKET=alexcrichton-test

cache:
  directories:
    - $HOME/.cargo
